package:
  name: pyncml
  version: "0.0.9"


source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - netcdf4
    - pytz
  run:
    - python
    - numpy
    - netcdf4
    - pytz

test:
  imports:
    - pyncml

about:
  home: https://github.com/axiom-data-science/pyncml
  license: MIT
  summary: 'A simple python library to apply NcML logic to NetCDF files.'
